version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  backend:
    build: ./api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./api/.env
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:
